name: CI

on: push

jobs:
  test-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check if schema is up to date
        run: make gen-schema && git diff --exit-code

      - name: Run chart unit tests
        run: make unit-test
